name: AprilsPhotos
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07302396069280803
title: 'AprilsPhotos - Portraits, Events, Fine Art'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5f4f6c'
    - '#a481b6'
    - '#000000'
    - '#ffffff'
    - '#c9a343'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.228041
  rhythmicContrast: 0
purpose: []
