name: AprilsPhotos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.07302396069280803
title: "April's Photos - Portraits, Events, Fine Art"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72843037-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5f4f6c'
    - '#a481b6'
    - '#000000'
    - '#ffffff'
    - '#c9a343'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
