analytics: {}
color:
  brandColors:
    - '#5f4f6c'
    - '#a481b6'
    - '#000000'
    - '#ffffff'
    - '#c9a343'
  brandStrength: 0.000845
  lightness: 1
  rhythmicContrast: 0
  saturation: 0.228041
cta: {}
layout_spectrum: 0.783784
name: AprilsPhotos
opengraph: {}
purpose: []
typography_spectrum: 0.07302396069280803
